version: "3.8"

services:
  artisan:
    build: .
    container_name: myc
    volumes:
      - ./:/var/www/html
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    container_name: myn
    depends_on:
      - artisan
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf